theme: jekyll-theme-minimal
encoding: UTF-8

burl: https://windows-2048.github.io
bdate: 2025-12-07

real_www: windows-2048.github.io

prod-url: https://windows-2048.github.io

github_star_counter: 180
github_fork_counter: 34
total_download_counter: 62947416
total_rating_counter: 4.7
upd_day_year: 07 2025

download_link_main: https://filedn.com/llBp1EbMQML0Hdv9A9SVo6b/The-Fastest-Mouse-Clicker-for-Windows/Installer_TheFastestMouseClickerv3_v3.0.0.0.msi
download_link_main_classic: https://filedn.com/llBp1EbMQML0Hdv9A9SVo6b/The-Fastest-Mouse-Clicker-for-Windows/Installer_TheFastestMouseClickerClassic64_v2.1.6.0.msi
download_link_mirror: https://filedn.com/llBp1EbMQML0Hdv9A9SVo6b/The-Fastest-Mouse-Clicker-for-Windows/Installer_TheFastestMouseClickerv3_v3.0.0.0.msi

app_version: 3.0.0.0
app_version_classic: 2.1.6.0
date_published: 2025-11-15
source_issues_url: https://github.com/windows-2048/The-Fastest-Mouse-Clicker-for-Windows/issues/

defaults:
    -
     scope:
         path: ""
     values:
         author: "me"
         layout: default
         lang: en
         base-url: "/"
    -
     scope:
         path: "es"
     values:
         lang: es
         base-url: "/es/"
    -
     scope:
         path: "pt"
     values:
         lang: pt
         base-url: "/pt/"

t:
    copyright_header:
        en: Copyright
        es: Derechos de autor
        pt: Direitos autorais
    copyright_text:
        en: Copyright (c) 2016-2025 by
        es: Derechos de autor (c) 2016-2025 por
        pt: Direitos autorais (c) 2016-2025 de
    sitemap_text:
        en: Site map
        es: Mapa del sitio
        pt: Mapa do site
    app_name:
        en: The Fastest Mouse Clicker for Windows version 3
        es: El Clicker de Ratón Más Rápido para Windows versión 3
        pt: O Mais Rápido Mouse Clicker para Windows versão 3
    app_name_classic:
        en: The Fastest Mouse Clicker for Windows Classic
        es: El Clicker de Ratón Más Rápido para Windows Clásico
        pt: O Mais Rápido Mouse Clicker para Windows Clássico
    download_html_main:
        en: '<div style="margin-top: -20px;margin-bottom: 20px;"><small>A brand new cross-platform app written from scratch utilizing <a href="https://doc.qt.io/archives/qt-5.15/classes.html" target="_blank">Qt</a>, <a href="https://github.com/kwhat/libuiohook" target="_blank">libuiohook</a> technologies. Versions for Linux, macOS are coming soon...</small></div>'
        es: '<div style="margin-top: -20px;margin-bottom: 20px;"><small>Una aplicación multiplataforma completamente nueva, escrita desde cero utilizando las tecnologías <a href="https://doc.qt.io/archives/qt-5.15/classes.html" target="_blank">Qt</a> y <a href="https://github.com/kwhat/libuiohook" target="_blank">libuiohook</a>. Próximamente estarán disponibles las versiones para Linux y macOS...</small></div>'
        pt: '<div style="margin-top: -20px;margin-bottom: 20px;"><small>Um aplicativo multiplataforma totalmente novo, escrito do zero utilizando as tecnologias <a href="https://doc.qt.io/archives/qt-5.15/classes.html" target="_blank">Qt</a> e <a href="https://github.com/kwhat/libuiohook" target="_blank">libuiohook</a>. Versões para Linux e macOS estarão disponíveis em breve...</small></div>'
    download_html_main_classic:
        en: '<div style="margin-top: -20px;margin-bottom: 20px;"><small>A classic Windows app without <a href="https://github.com/windows-2048/The-Fastest-Mouse-Clicker-for-Windows/issues/20" target="_blank">GitHub issue #20</a>: Keyboard & Mouse locked and hardly able to control when pressing TOGGLE stop key.</small></div>'
        es: '<div style="margin-top: -20px;margin-bottom: 20px;"><small>Una aplicación clásica de Windows sin <a href="https://github.com/windows-2048/The-Fastest-Mouse-Clicker-for-Windows/issues/20" target="_blank">GitHub Problema #20</a>: El teclado y el ratón se bloquean y apenas se pueden controlar al pulsar la tecla de parada TOGGLE.</small></div>'
        pt: '<div style="margin-top: -20px;margin-bottom: 20px;"><small>Um aplicativo clássico do Windows sem o <a href="https://github.com/windows-2048/The-Fastest-Mouse-Clicker-for-Windows/issues/20" target="_blank">problema #20 do GitHub</a>: Teclado e mouse bloqueados e praticamente impossíveis de controlar ao pressionar a tecla de parada TOGGLE.</small></div>'
    home:
        en: "/"
        es: "/es/"
        pt: "/pt/"
    home_app:
        en: "/The-Fastest-Mouse-Clicker-for-Windows/"
        es: "/es/El-Clicker-de-Raton-Mas-Rapido-para-Windows/"
        pt: "/pt/O-Mais-Rapido-Mouse-Clicker-para-Windows/"
    author_name:
        en: Open Source Developer Masha Novedad, the author of The Fastest Mouse Clicker for Windows
        es: Masha Novedad, desarrolladora de código abierto, autora de El Clicker de Ratón Más Rápido para Windows
        pt: Desenvolvedor de código aberto Masha Novedad, o autor do Mais Rápido Mouse Clicker para Windows
    title:
        en: The Fastest Mouse Clicker for Windows | Official Site
        es: El Clicker de Ratón Más Rápido para Windows | Sitio Oficial
        pt: O Mais Rápido Mouse Clicker para Windows | Site Oficial
    description:
        en: The fastest auto-clicker for Windows PC. 100000 clicks per second reached by arrayed Win32 SendInput(). GUI, command line, record/play sequences of clicks
        es: El clicker automático más rápido para Windows PC. 100000 clics por segundo por Win32 SendInput(). GUI, línea de comandos, secuencias de grabación/reproducción
        pt: O clique automático mais rápido para Windows PC. 100000 cliques por segundo alcançado por Win32 SendInput(arrayed). GUI, linha de comando, sequências de registro/jogo de cliques
    description_rich:
        en: The fastest auto-clicker for Windows PC. 100000 clicks per second reached by arrayed Win32 <a href="https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput" target="_blank">SendInput()</a>. GUI, command line, random clicks, and record/play sequences of clicks
        es: El clicker automático más rápido para Windows PC. 100000 clics por segundo alcanzados por Win32 <a href="https://learn.microsoft.com/es-es/windows/win32/api/winuser/nf-winuser-sendinput" target="_blank">SendInput()</a> en matriz. GUI, línea de comandos, clics aleatorios y secuencias de clics de grabación/reproducción
        pt: O clique automático mais rápido para Windows PC. 100000 cliques por segundo alcançado por Win32 <a href="https://learn.microsoft.com/pt-br/windows/win32/api/winuser/nf-winuser-sendinput" target="_blank">SendInput()</a>. GUI, linha de comando, sequências de registro/jogo de cliques
    download_the_latest_version:
        en: Download the latest version
        es: Descarga la última versión
        pt: Baixe a versão mais recente
    html_lang:
        en: en
        es: es
        pt: pt
    read_text:
        en: read
        es: lee
        pt: ler
    mirror_text:
        en: mirror
        es: espejo
        pt: espelho
    follow_text:
        en: Follow
        es: Sigue
        pt: Siga
    changelog_text:
        en: ChangeLog
        es: RegistroDeCambios
        pt: AlterarORegisto
    updated_text:
        en: Updated
        es: Actualizado
        pt: Atualizado
    updated_month:
        en: Dec
        es: Diciembre
        pt: Dezembro
    lang_countries:
        en:
            -
                name: us
            -
                name: gb
            -
                name: au
            -
                name: in
        es:
            -
                name: es
            -
                name: mx
            -
                name: ar
            -
                name: co
            -
                name: cl
        pt:
            -
                name: pt
            -
                name: br
